### ISSUE TITLE
Enhancements.

### ISSUE THREAD

**Issue by sjeffrey101** [mattsaxon/HASS-SpeakercraftMediaPlayer#10]
hi matt

ok had a chance to test your code.  Works really well.  thanks for making this so much better.

i think we should make the following changes. (not in this order or priority)  and once i figure out github i can contribute to this.

* move the device code to pypi
* move the setup of component to init rather than in media player - this will allow additional entity types to be created easier.
* get it to register as a device.  Not sure if it should be a single device, or multiple to allow for areas for different zones.  Gather device info.  Unique info could be comport.
* Add button for All Off.
* remove all the master on/off  power_target - this should be achievable through automations, rather then in the component.
* fire an event when trying to turn on a zone (so an automation can turn on the smart power socket)
* change tuner message from warn to debug. (too much in the log)
* im not sure the default volume is working any more.
* add input_numbers (sliders) for bass and treble
* add buttons for terble flat and bass flat
* independent default source and volume for different zones.
* setup in configuration.yaml as a platform rather than media_player section, so it can create the media players, switches, buttons etc.
* eventually setup as gui rather then configuration.yaml

some of these could be breaking changes, or have the potential to, so probably priority would be to do them before getting many users. 

what are your thoughts?

kind regards

stuart

**Comment by mattsaxon** [comment]
This looks a good set of changes to me.

We should split each items into a separate issue, the Pypi one already has an issue.

how’s the performance of the component for you, does it render your ESP32 solution unnecessary? I still think we ideally support this so people who are not lucky enough to have their HA unit by their MZC can still be supported .

**Comment by sjeffrey101** [comment]
hi Matt,

yeah i didnt want to create seperate posts until  i got your feed back (didnt want to spam you).

Performance wise its very quick.  Im ditching the ESP32 solution in favour of this - 1 less thing to plug in and manage.  

there might be better ways of handling a remote unit - I once tried a serial to ethernet, but it wasnt fast enough to handle the 11/13 send window.  But it probably supports the flow control in its own firmware, so it probably could have worked had i realised.

**Comment by mattsaxon** [comment]
Yes I was thinking about some sort of remote serial using ser2net or socat.

one issue to work through is that I think this approach would need an HA add-in as Hassio doesn’t have these components installed in the base Linux image.

How do you have HA installed?

**Comment by sjeffrey101** [comment]
im installed using docker on my synology.  But i have a spare mini pc i will eventually move a full HASSOS onto.

i dont think it would need an addin as the ser2net would be at the remote end.  From what i understand the url in serial_asyncio.open_serial_connection can connect to tcp also?  (but i might be wrong).

**Comment by mattsaxon** [comment]
Ah, ok that makes sense. As you say it would be remote end, so even if pyserial doesn’t directly support, we could just change to a socket connection.

**Comment by mattsaxon** [comment]
I've created issues for each of the items that are outstanding and will close this one
