### ISSUE TITLE
Refine Master-Off handling

### ISSUE THREAD

**Issue by mattsaxon** [mattsaxon/HASS-SpeakercraftMediaPlayer#17]
@sjeffrey101 suggested we should add a button for all off

**Comment by mattsaxon** [comment]
I propose the best way to achieve this is to use the [media group](https://www.home-assistant.io/integrations/media_player.group/) integration.

This is a zero code option and supports power on, power off, mute all and group volume set.

@sjeffrey101 what is your view on this? If you are supporting, we can remove quite a bit of the code for masteroff as we move to events as part of https://github.com/mattsaxon/HASS-SpeakercraftMediaPlayer/issues/18

**Comment by sjeffrey101** [comment]
could use media group.  but party mode kinda achieves that also.

i think  we just need a button for "master off"

**Comment by mattsaxon** [comment]
Party Mode does most of it as you say, but has no master off.

The benefit of media group is that if you don't happen to be in party mode, then it provides a "mute all" too, which is, for me, more handy.

I can see a use case for both.

**Comment by mattsaxon** [comment]
discussions in #25 suggest we may keep this functionality

**Comment by sjeffrey101** [comment]
ok just done a button for all zones off.
once that PR is committed then i think this can be closed also.
