### ISSUE TITLE
Refine approach for Master-On controlling a smart plug for amplifier power

### ISSUE THREAD

**Issue by mattsaxon** [mattsaxon/HASS-SpeakercraftMediaPlayer#18]
@sjeffrey101  suggested;

* remove all the master on/off power_target - this should be achievable through automations, rather then in the component.
* fire an event when trying to turn on a zone (so an automation can turn on the smart power socket)

**Comment by mattsaxon** [comment]
Discussions in #25 suggest we may keep this functionality.

**Comment by sjeffrey101** [comment]
this has now been resolved.  

a new class, for the controller has been created, which has a callback for when the first zone is requested power or the last zone is turned off.

on the ha side there is a power handler class which then responds to the call back and turned the smart plug on/off.

there is a delay of 60 seconds to turn off so its not turning the mains power on/off repeatedly.
