### ISSUE TITLE
Use device_state_attributes is deprecated from HA 2021.12

### ISSUE THREAD

**Issue by mattsaxon** [mattsaxon/HASS-SpeakercraftMediaPlayer#2]
Easy fix to replace with "extra_state_attributes", but need to check other users are at this latest version before closing.

**Comment by mattsaxon** [comment]
@sjeffrey101 can you confirm you are on HA2021.12, so I can close this now?

**Comment by sjeffrey101** [comment]
yep i am.  close this.

**Comment by mattsaxon** [comment]
Added home assistant minimum version to hacs.json
