### ISSUE TITLE
Make entities optional.

### ISSUE THREAD

**Issue by sjeffrey101** [mattsaxon/HASS-SpeakercraftMediaPlayer#32]
Add to configuration a way to make features optional.

suggest that by default the following isnt included.

- master power off button
- party mode switches
- tone sliders
- tone up down buttons
- tone flat buttons

then we enable by adding to 

speakercraft_media:
    options:
        - master power off button
        - party mode switches
        - tone sliders
        - tone up down buttons
        - tone flat buttons

**Comment by mattsaxon** [comment]
What's the overhead of leaving these entities there?

**Comment by sjeffrey101** [comment]
good question.  I dont necessarily think there is an overhead, just means lots of entities which may not be needed.  particularly the buttons - but these could be useful to someone.

to be honest i dont mind them left in, as they dont need including on dashboards, just thought it was starting to get entity happy.

maybe a non issue. - more work then its worth

**Comment by mattsaxon** [comment]
My feeling is that is unnecessarily complex. As I've not seen any other components do this, I feel that its a non issue for performance. I also think in the front end, the search is good enough that again it's a non issue

**Comment by sjeffrey101** [comment]
ok cool- agree.

should we close this.

**Comment by mattsaxon** [comment]
Yes, I think so.
