### ISSUE TITLE
Log Errors

### ISSUE THREAD

**Issue by BrentMcInnes** [mattsaxon/HASS-SpeakercraftMediaPlayer#37]
I'm getting some feedback from the mzc66 as far as volume levels but I can't control it.  Plus the source lights on my wall panels are flashing when the MZC is connected to my Pi.  I'm getting these log errors below - any ideas why?

This error originated from a custom integration.

Logger: custom_components.speakercraft_media.speakercraft_media
Source: custom_components/speakercraft_media/speakercraft_media.py:426
Integration: Speakercraft Media Player (documentation, issues)
First occurred: 7:26:35 PM (31797 occurrences)
Last logged: 7:28:21 PM

throw away early trim 65
throw away early trim 72
throw away early trim 73
throw away early trim 69
throw away early trim 6f

--------------------------------------------

This error originated from a custom integration.

Logger: custom_components.speakercraft_media.speakercraft_media
Source: custom_components/speakercraft_media/speakercraft_media.py:408
Integration: Speakercraft Media Player (documentation, issues)
First occurred: 7:26:43 PM (49 occurrences)
Last logged: 7:27:02 PM

length too long, assume incorrect and find next message 557d

**Comment by sjeffrey101** [comment]
hi @BrentMcInnes 

That's disappointing, it hasn't just worked for you.

Can you confirm what firmware you are on?  It should be reported when the component first starts - provided its receiving messages.  Or you can get from EZtools.  Should be 2.2.8 for latest.

Which pi are you running on?

and what HA version?

I'd expect some early trim when the component first loads, as it may have some incomplete messages on the serial.  but once its processed the first complete message we shouldnt get that throw away again.  -  is it when it first loads for you or after?  I think @mattsaxon  gets the odd one on his pi,  which makes me wonder if the PI cant keep up with the serial.   - have you checked your connections also.

are you using a USB to serial adapter - do you know what type?  I stick to FTDI - as people say they are reliable.

odd the source lights would flash.

i think we my need to get more info from the debug logs.  there is a section in the readme that details how to turn these on for the component.  Then we might get more idea about what is been recieved and sent.

Stu

**Comment by BrentMcInnes** [comment]
I think I have it working now - I reflashed the MZC to 2.2.8 then uploaded my .etp file to MZC - that stopped the source lights from flashing.  The rebooted the pi and now I have control over the MZC from HA.  Thanks!

**Comment by mattsaxon** [comment]
Excellent news. I'm closing this and will update the readme to include the requirement for 2.2.8

**Comment by sjeffrey101** [comment]
great.  glad you got it working
