### ISSUE TITLE
Can't turn on the media_player.lounge_speakers ??

### ISSUE THREAD

**Issue by brinzlee** [mattsaxon/HASS-SpeakercraftMediaPlayer#46]
Hi…I am trying to implement your great code…but have come up againt an issue I’m not sure how to get around…
I am using an usb ftdi-rs232 adapter to a 3.5mm plug on the control port. I can update the firmware on the speakercraft amp which is an MZC-66.
I can implement the the controls but when it comes to enabling the zones for example
media_player.lounge_speakers
to turn on it just does not respond. I can get the party zone to work and I can see all the zones switch on by the leds on the amp but I can’t get it to switch on via media_player.. any ideas…?

See my attatched log
[New Text Document (5).txt](https://github.com/mattsaxon/HASS-SpeakercraftMediaPlayer/files/8453448/New.Text.Document.5.txt)

**Comment by mattsaxon** [comment]
Please don't paste logs in full, instead attach log files to the conversation. This makes the conversation easier to read and the files easier to process.

**Comment by brinzlee** [comment]
Sorry
Have amended as necessary

**Comment by mattsaxon** [comment]
OK, so looks like the software is working correctly, messages sent and confirmations received. First guess is that you have some setup on the MZC that doesn't like this.

Do you have physical controllers that are able to execute the commands you are attempting via this integration? (Some people using this software don't, but the MZC needs to be setup as if you do)

**Comment by mattsaxon** [comment]
Looking further, it does look like you don't have it setup right.....

When I start-up HA, even before I send any commands, each enabled zone reports back to the software its status, I cant see that happening in your log. Since I can however see data flowing in both directions, send command and received, then I suspect the MZC zones are not setup using EZ Tools.

**Comment by brinzlee** [comment]
OK so I only bought the amp yesterday....I have no keypads to control the zones but I did what I thought was set the inputs and zones up using EZ tools. I have then uploaded this to the amp as well as uploading the latest firmware to the amp too

**Comment by mattsaxon** [comment]
Importantly you need to add keypads if I recall. You should be able to verify this is all working with the 'MZC emulator' which is part of the EZ tools download, again If I recall correctly.

Once you have verified this all works, the software should just work!

**Comment by sjeffrey101** [comment]
i'd start with the example project in ez-tools, leave it as is and load that to the controller.

assuming your on the right firmware that should do the trick nicely.

**Comment by brinzlee** [comment]
Many thanks for your help....I added the mode3.1 controller to the setup and all is working sweetly now......I have another 3 speakercraft amps on order now....for my friends....thanks once again
